pipeline:

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.m2
    volumes:
      - /tmp/cache:/cache
    when:
      event: [ push ]

  db_test:
    image: maven:3.6.0-jdk-8-alpine
    commands:
      - ./drone-mvn-cache.sh
      - cd pg
      - ./db-create.sh -Denv=ci
      - ./migrate-up.sh -Denv=ci
      - ./test.sh -Denv=ci
    when:
      event: [ push ]
      branch:
        exclude: master

  app_unit-test:
    image: maven:3.6.0-jdk-8-alpine
    commands:
      - ./drone-mvn-cache.sh
      - cd app
      - ./test.sh
      - mkdir -p unit-tests && cp ./target/jacoco.exec ./unit-tests
    when:
      event: [ push ]
      branch:
        exclude: master

  app_integration-test:
    image: maven:3.6.0-jdk-8-alpine
    commands:
      - ./drone-mvn-cache.sh
      - cd app
      - ./integration-test.sh -Denv=ci &> integration-test.log
      - mkdir -p integration-tests && cp ./target/jacoco.exec ./integration-tests
    when:
      event: [ push ]
      branch:
        exclude: master

  #upload_to_sonar:
  #  image: maven:3.6.0-jdk-8-alpine
  #  commands:
  #    - ./drone-mvn-cache.sh
  #    - cd app
  #    - mvn sonar:sonar
  #  when:
  #    event: [ push ]
  #    branch:
  #      exclude: master

  print_log:
    image: maven:3.6.0-jdk-8-alpine
    commands:
      - touch ./app/integration-test.log
      - tail -n 500 ./app/integration-test.log
    when:
      event: [ push ]
      status: [ success, failure ]
      branch:
        exclude: master

  db_migration_staging:
    image: maven:3.6.0-jdk-8-alpine
    commands:
      - ./drone-mvn-cache.sh
      - cd pg
      - ./db-create.sh -Denv=development
      - ./migrate-up.sh -Denv=development
    when:
      event: [ push ]
      branch: master

  db_mock_migration_staging:
    image: maven:3.6.0-jdk-8-alpine
    commands:
      - ./drone-mvn-cache.sh
      - cd pg
      - ./db-create.sh -Denv=development-mock
      - ./db-drop.sh -Denv=development-mock
      - ./db-create.sh -Denv=development-mock
      - ./migrate-up.sh -Denv=development-mock
      - ./migrate-bootstrap.sh --force -Denv=development-mock
    when:
      event: [ push ]
      branch: master

  db_migration_sandbox:
    image: maven:3.6.0-jdk-8-alpine
    commands:
      - ./drone-mvn-cache.sh
      - cd pg
      - ./db-create.sh -Denv=sandbox
      - ./migrate-up.sh -Denv=sandbox
    when:
      event: [ tag ]
      ref: refs/tags/snapshot*

  build:
    image: maven:3.6.0-jdk-8-alpine
    commands:
      - ./drone-mvn-cache.sh
      - cd app && ./package.sh
    when:
      event: [ push ]
      branch: master

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./.m2
    volumes:
      - /tmp/cache:/cache
    when:
      event: [ push ]

  publish_image:
    registry: mccontainerregistry.azurecr.io
    image: plugins/docker
    repo: mccontainerregistry.azurecr.io/api-prepago
    tags:
      - ${DRONE_COMMIT_SHA}
    secrets: [ docker_username, docker_password ]
    when:
      event: [ push ]
      branch: master

  deploy_to_staging:
    image: mccontainerregistry.azurecr.io/tools/drone-phoenix:1.0.0
    cluster: staging
    vars:
      - IMAGE=mccontainerregistry.azurecr.io/api-prepago:${DRONE_COMMIT_SHA}
      - DB_NAME=prepago_api_dev
      - API_ENVIRONMENT=development
      - DB_USERNAME=prepago
      - DB_PASSWORD=N8BC2VQ74PrGv4SeXdHvcT8VPT7pTWU2
      - DB_HOST_FQDN=prepaid-postgresql-staging.postgres.database.azure.com
      - DB_HOST_NAME=prepaid-postgresql-staging
    when:
      event: [ push ]
      branch: master

  deploy_mock_to_staging:
    image: mccontainerregistry.azurecr.io/tools/drone-phoenix:1.0.0
    cluster: staging
    template: deployment-mock.staging.yml
    vars:
      - IMAGE=mccontainerregistry.azurecr.io/api-prepago:${DRONE_COMMIT_SHA}
      - DB_NAME=prepago_api_dev_mock
      - API_ENVIRONMENT=development-mock
      - DB_USERNAME=prepago
      - DB_PASSWORD=N8BC2VQ74PrGv4SeXdHvcT8VPT7pTWU2
      - DB_HOST_FQDN=prepaid-postgresql-staging.postgres.database.azure.com
      - DB_HOST_NAME=prepaid-postgresql-staging
    when:
      event: [ push ]
      branch: master

  deploy_virtual_service_to_staging:
    image: mccontainerregistry.azurecr.io/tools/drone-phoenix:1.0.0
    cluster: staging
    template: virtual-service.staging.yml
    when:
      event: [ push ]
      branch: master

  deploy_destination_rule_to_staging:
    image: mccontainerregistry.azurecr.io/tools/drone-phoenix:1.0.0
    cluster: staging
    template: destination-rule.staging.yml
    when:
      event: [ push ]
      branch: master

  deploy_to_sandbox:
    image: mccontainerregistry.azurecr.io/tools/drone-phoenix:1.0.0
    cluster: sandbox
    vars:
      - IMAGE=mccontainerregistry.azurecr.io/api-prepago:${DRONE_COMMIT_SHA}
      - DB_NAME=prepago_api
      - API_ENVIRONMENT=sandbox
    consul_kv: env/sandbox.env
    when:
      event: [ tag ]
      ref: refs/tags/snapshot*

  deploy_to_production:
    image: mccontainerregistry.azurecr.io/tools/drone-phoenix:1.0.0
    cluster: production
    vars:
      - IMAGE=mccontainerregistry.azurecr.io/api-prepago:${DRONE_COMMIT_SHA}
    when:
      event: [ tag ]
      ref: refs/tags/release*

  slack:
    image: mccontainerregistry.azurecr.io/tools/drone-slack:1.0.0
    channel: drone_deployments
    icon_emoji: ":package:"
    when:
      status: [ success, failure ]

services:
  database:
    image: postgres:9.6.3-alpine
    when:
      event: [ push ]
      branch:
        exclude: master

  queue:
    image: webcenter/activemq:5.14.3
    environment:
      - ACTIVEMQ_CONFIG_MINMEMORY=256
      - ACTIVEMQ_CONFIG_MAXMEMORY=512
      - ACTIVEMQ_ADMIN_LOGIN=system
      - ACTIVEMQ_ADMIN_PASSWORD=jdxnhyr674Hbf$5cx0
    when:
      event: [ push ]
      branch:
        exclude: master
