---
apiVersion: v1
kind: Namespace
metadata:
  name: api-prepaid
  labels:
    istio-injection: enabled
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-prepaid
  namespace: api-prepaid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-prepaid
  template:
    metadata:
      labels:
        app: api-prepaid
        version: v1
    spec:
      containers:
      - name: api-prepaid
        image: ${IMAGE}
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      imagePullSecrets:
        - name: container-reg-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: api-prepaid
  labels:
    app: api-prepaid
  namespace: api-prepaid
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: api-prepaid
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: api-prepaid-gateway
  namespace: api-prepaid
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https-api-prepaid
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - api.${CLUSTER_ENVIRONMENT}.${CLUSTER_DOMAIN}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-prepaid-vts
  namespace: api-prepaid
spec:
  hosts:
  - api.${CLUSTER_ENVIRONMENT}.${CLUSTER_DOMAIN}
  gateways:
  - api-prepaid-gateway
  http:
  - match:
    - uri:
        prefix: /prepaid/1.0
    rewrite:
      uri: /api-prepaid-1.0/1.0/prepaid
    route:
    - destination:
        host: api-prepaid
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: db
  namespace: api-users
spec:
  hosts:
  - "prepaid-postgresql-staging.postgres.database.azure.com"
  location: MESH_EXTERNAL
  ports:
  - number: 5432
    name: tcp-api-users-db
    protocol: TCP
