---
apiVersion: v1
kind: Namespace
metadata:
  name: api-prepaid
  labels:
    istio-injection: enabled
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-prepaid
  namespace: api-prepaid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-prepaid
  template:
    metadata:
      labels:
        app: api-prepaid
        version: v1
    spec:
      containers:
      - name: api-prepaid
        image: ${IMAGE}
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      imagePullSecrets:
        - name: container-reg-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: api-prepaid
  labels:
    app: api-prepaid
  namespace: api-prepaid
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: api-prepaid
---
