---
apiVersion: v1
kind: Namespace
metadata:
  name: prepaid
  labels:
    istio-injection: enabled
---
###########
# Service #
###########
apiVersion: v1
kind: Service
metadata:
  name: api-prepaid
  labels:
    app: api-prepaid
    service: api-prepaid
  namespace: prepaid
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: api-prepaid
---
##############
# Deployment #
##############
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-prepaid
  namespace: prepaid
  labels:
    app: api-prepaid
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-prepaid
      version: v1
  template:
    metadata:
      labels:
        app: api-prepaid
        version: v1
    spec:
      containers:
      - name: api-prepaid
        image: ${IMAGE}
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
          - name: DB_USERNAME
            value: ${DB_USERNAME}@${DB_HOST_NAME}
          - name: DB_PASSWORD
            value: ${DB_PASSWORD}
          - name: DB_NAME
            value: ${DB_NAME}
          - name: DB_HOST_FQDN
            value: ${DB_HOST_FQDN}
          - name: API_ENVIRONMENT
            value: ${API_ENVIRONMENT}
          - name: TENPO_USER_API_URL
            value: "http://${TENPO_USER_API_HOST}/v1/user-management"
          - name: TECNOCOM_MOCK_IMPL
            value: "false"
          - name: TECNOCOM_API_KEY
            value: ${TECNOCOM_API_KEY}
          - name: TECNOCOM_API_URL
            value: ${TECNOCOM_API_URL}
          - name: TECNOCOM_CHANNEL
            value: ${TECNOCOM_CHANNEL}
          - name: TECNOCOM_CODENT
            value: ${TECNOCOM_CODENT}
          - name: TECNOCOM_ORDER
            value: ${TECNOCOM_ORDER}
      imagePullSecrets:
        - name: container-reg-credentials
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: api-prepaid-se-tecnocom
  namespace: prepaid
spec:
  hosts:
  - "tc.uat.multicajadigital"
  addresses:
  - "200.111.44.187"
  location: MESH_EXTERNAL
  ports:
  - number: 9080
    name: http-api-prepaid-tecnocom
    protocol: HTTP
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: api-prepaid-user-management
  namespace: prepaid
spec:
  hosts:
  - "40.70.68.63"
  location: MESH_EXTERNAL
  ports:
  - number: 8080
    name: tcp-api-prepaid-user-management
    protocol: TCP
  resolution: NONE
---
